### PR TITLE
Fixed 2 bugs and introduced new feature

### PR DESCRIPTION
**Pull request by Sombrer0Dev**
Hi @ @WolfeCub, wanted to contribute to your plugin. 
In this pr i fixed a bug that was caused by overwriting M variable and i added vim notify call when marks list is empty.
Also i added a feature to list marked dirs, because grapple and harpoon allows you to mark netrw or oil buffers.

Notify message:
image

Harpeek list with dirs: 
image

### CODE REVIEW

**Comment by Sombrer0Dev** [comment]
Closes #1

**Comment by Sombrer0Dev** [comment]
I think another feature I could add is a setting that allows user to choose which path format harpeek will display (full/short/from home)
Also I will be testing it on windows tomorrow, to ensure that my path substitution method is ok

**Comment by WolfeCub** [comment]
Thanks for contributing!

I've got some local changes that I'm working on for providing a few different format options. 

When I get home tonight I'll work on merging this into the changes I have locally. I think that will also address your other comment.

**Comment by WolfeCub** [comment]
https://github.com/WolfeCub/harpeek.nvim/commit/fa25874a9d37cbe3faa222f46fd289a6176f02a1 incorporates your fix for the module name & supports multiple path formatting options (I want to expand on this a bit more).

I'll pull in the oil support as well.

**Comment by WolfeCub** [comment]
https://github.com/WolfeCub/harpeek.nvim/commit/731013057950cd249295317ac27dcf2640075880 here's the oil logic. 

I had to rework it a bit to support the new multiple path options.

**Comment by avijit14** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
superoo7, @bobnautic, @dendisuhubdy, @ShevonKuan, @kendewitt, @nashsu, @JRizzled, @Varuzoli, @Emzy, @chouchou312, @marcoaubr, @lc6chang, @aksxaay, @tensaix2j, @paderma, @jerryleooo, @dryaf, @kidmam, @jeffersfp, @PatrickRoethlisberger, @d3l33t, @rkapdi, @L1u2c3a4s5862, @dn365, @PascalDierich, @lindseyesch, @cGitHub123, @christianboyle, @Gituser143, @Sporesirius, @mumblez, @zyp001a, @luisnquin, @nguyenminhvn16, @danielmu22, @xaviablaza, @syphrpunk, @jatniel, @valentingue, @lilyDong, @matlegit, @ron-roc, @Evalir, @aglyzov, @starkxun, @colorfulvoid, @ironsoul0, @drsect0r, @renanrrodrigues, @Jacknes

**Pull request closed without merging**
